# Lesson 1: Matrix Math and Numpy Refresher

## Data Has Dimensions

**Scalars** - single value, such as 1, 2.4, -3
Scalars have zero dimensions

**Vectors** - lists of values, can be row vectors or columns vectors
Scalars have one dimension: length

**Matrices** - 2D grid of values, shaped described in numbers of rows and columns

**Tensors** - Any n dimensional collection of values


## Introducting NumPy

In [1]:
import numpy as np

#### Scalars

In [2]:
s = np.array(5)

In [5]:
s.shape

()

#### Vectors

In [6]:
v = np.array([1, 2, 3])

In [8]:
v

array([1, 2, 3])

In [7]:
x = v[1]

In [9]:
x

2

In [10]:
v[1:]

array([2, 3])

#### Matrices

In [11]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [13]:
m.shape

(3, 3)

#### Tensors

In [14]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [16]:
t.shape

(3, 3, 2, 1)

In [17]:
t[2][2][1][0]

17

#### Changing Shapes

In [18]:
v = np.array([1,2,3,4])

In [19]:
x = v.reshape(1, 4)

In [21]:
x.shape

(1, 4)

In [22]:
x = v[None, :]

In [23]:
x

array([[1, 2, 3, 4]])

## Element-wise Operations

#### The Python Way (without NumPy)

In [24]:
values = [1, 2, 3, 4, 5]
for i in range(len(values)):
    values[i] += 5

In [25]:
values

[6, 7, 8, 9, 10]

#### The NumPy way

In [27]:
values = [1, 2, 3, 4, 5]
values = np.array(values) + 5

In [28]:
values

array([ 6,  7,  8,  9, 10])

In [30]:
some_array = [2, 5, 2, 5]

In [34]:
x = np.multiply(some_array, 5)
x = some_array * 5

In [35]:
x

[2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5, 2, 5]

To set every element in a matrix to zero, no matter its dimensions:

In [38]:
c = np.array([[2,3,6],[4,5,9],[1,8,7]])

In [39]:
c

array([[2, 3, 6],
       [4, 5, 9],
       [1, 8, 7]])

In [40]:
c *= 0

In [42]:
c

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])